version: "3.9"

networks:
  backbone:
    driver: bridge
#  wg-network:
#    ipam:
#      config:
#        - subnet: 192.168.99.0/24

services:
  # Downloaders
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    network_mode: service:wireguard
    depends_on:
      - wireguard
    volumes:
      - /media/faiyt/f/config/sabnzbd:/config
      - /media/faiyt/d/downloads:/downloads #optional
      - /media/faiyt/d/downloads/incomplete:/incomplete-downloads #optional
    #    ports:
    #  - 9191:8080
    #       - 8181:8080
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
  # image: cr.hotio.dev/hotio/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8383
    depends_on:
      - wireguard
    network_mode: service:wireguard
    volumes:
      - /media/faiyt/f/config/qbittorrent:/config
      - /media/faiyt/d/downloads:/downloads
    #    ports:
    #      - 8381:8383
    #      - 6879:6881
    #      - 6879:6881/udp
    restart: unless-stopped
  metube: # Youtube DL
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /media/faiyt/d/downloads/youtube:/downloads
  # VPN
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - backbone
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VPN_PROTOCOL=wireguard
    ports:
      - 51820:51820/udp
      - 8181:8080
      - 8383:8383
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /lib/modules:/lib/modules
      - /media/faiyt/f/config/wireguard:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    #      - net.ipv6.conf.all.disable_ipv6=1
    #      - net.ipv6.conf.default.disable_ipv6=1
    #   command: "sleep 10 && curl -w \"\n\" ifconfig.me"
    restart: unless-stopped

# Finders
  sonarr: # https://hub.docker.com/services/sonarr
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    cpu_count: 4
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /media/faiyt/f/config/sonarr:/config
      - /media/faiyt/d/tv:/tv #optional
      - /media/faiyt/e/tv:/e/tv #optional
      - /media/faiyt/d/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
# Getters
  radarr: # https://hub.docker.com/r/linuxserver/radarr
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /media/faiyt/f/config/radarr:/config
      - /media/faiyt/g/movies:/movies #optional
      - /media/faiyt/e/movies:/e/movies #
      - /media/faiyt/f/movies:/f/movies
      - /media/faiyt/d/downloads:/downloads #optional
     # - /media/faiyt/e/movies:/e/movies
    ports:
      - 7878:7878
    restart: unless-stopped
  lidarr: # https://hub.docker.com/r/linuxserver/lidarr
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /media/faiyt/f/config/lidarr:/config
      - /media/faiyt/d/music:/music #optional
      - /media/faiyt/d/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
  bazarr: # https://hub.docker.com/r/linuxserver/bazarr
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /media/faiyt/f/config/bazarr:/config
      - /media/faiyt/g/movies:/movies #optional
      - /media/faiyt/d/tv:/tv #optional
      - /media/faiyt/e/tv:/e/tv
    ports:
      - 6767:6767
    restart: unless-stopped
  readarr: # https://hub.docker.com/r/linuxserver/readarr
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /media/faiyt/f/config/readarr:/config
      - /media/faiyt/g/books:/books #optional
      - /media/faiyt/d/downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /media/faiyt/f/config/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /media/faiyt/f/config/organizr:/config
    ports:
      - 80:80
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP, it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8080:80/tcp"
    environment:
      TZ: 'America/Chicago'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - '/media/faiyt/f/config/pihole/main:/etc/pihole'
      - '/media/faiyt/f/config/pihole/dns:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
  # Logging
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    restart: unless-stopped
#  ersatztv: #Fake TV
#    container_name: ersatztv
#    network_mode: host
#    image: jasongdove/ersatztv:develop-nvidia
#    environment:
#      - TZ=America/Chicago
#    ports:
#      - 8409:8409
#    volumes:
#      - /media/faiyt/f/config/ersatztv:/root/.local/share/ersatztv
#      - /media/faiyt/d/videos/:/media:ro
#      - /media/faiyt/g/movies:/d/movies
#      - /media/faiyt/d/tv:/d/tv
#      - /media/faiyt/d/music:/d/music
#      - /media/faiyt/e/movies:/e/movies
#      - /media/faiyt/e/tv:/e/tv
#    restart: unless-stopped
  calibre-web: # Book Reader App
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
#      - /media/faiyt/f/config/calibre:/config
      - /media/faiyt/d/books/written-library:/config
    ports:
      - 8083:8083
    restart: unless-stopped
  swag: # NGINX / Lets Encrypt Config
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=faiyts.media
      - SUBDOMAINS=www,movies,tv,books,subtitles,read,router,find,vpn,block,plex,torrent,usenet,watch,logs,channels,music,listen,cloud
      - VALIDATION=dns
      - DNSPLUGIN=digitalocean #optional
    #        - DUCKDNSTOKEN=<token> #optional
      - EMAIL=me@faiyts.media #optional
    #        - DHLEVEL=2048 #optional
    #        - ONLY_SUBDOMAINS=false #optional
    #        - EXTRA_DOMAINS=<extradomains> #optional
    #        - STAGING=false #optional
    volumes:
      - /media/faiyt/f/config/swag:/config
    ports:
      - 443:443
    #        - 80:80 #optional
    restart: unless-stopped
  # Ensures DNS Matches local public ip
  dyndns:
    container_name: dyndns
    image: tunix/digitalocean-dyndns
    environment:
      - DIGITALOCEAN_TOKEN=${DIGITAL_OCEAN_TOKEN}
      - DOMAIN=faiyts.media
      - NAME=www;movies;tv;books;read;router;vpn;subtitles;block;find;plex;torrent;usenet;watch;logs;channels;music;listen;cloud
      - SLEEP_INTERVAL=300
      - REMOVE_DUPLICATES=true
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    network_mode: host
    cpu_count: 4
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=latest
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /media/faiyt/f/config/plex:/config
      - /media/faiyt/f/config/plex/transcode:/transcode
      - /media/faiyt/d/tv:/d/tv
      - /media/faiyt/g/movies:/d/movies
      - /media/faiyt/d/music:/d/music
      - /media/faiyt/e/movies:/e/movies
      - /media/faiyt/f/movies:/f/movies
      - /media/faiyt/e/tv:/e/tv
    restart: unless-stopped
#  tdarr:
#    container_name: tdarr
#    image: ghcr.io/haveagitgat/tdarr:latest
#    restart: unless-stopped
#    network_mode: bridge
#    ports:
#      - 8265:8265 # webUI port
#      - 8266:8266 # server port
#      - 8267:8267 # Internal node port
#      - 8268:8268 # Example extra node port
#    environment:
#      - TZ=Europe/London
#      - PUID=1000
#      - PGID=1000
#      - UMASK_SET=002
#      - serverIP=0.0.0.0
#      - serverPort=8266
#      - webUIPort=8265
#      - internalNode=true
#      - nodeID=MyInternalNode
#    volumes:
#      - /media/faiyt/f/config/tdarr/server:/app/server
#      - /media/faiyt/f/config/tdarr/configs:/app/configs
#      - /media/faiyt/f/config/tdarr/logs:/app/logs
#      - /d:/d
#      - /e:/e
#      - /transcode_cache:/temp
#    # node example
#  tdarr-node:
#      container_name: tdarr-node
#      image: ghcr.io/haveagitgat/tdarr_node:latest
#      restart: unless-stopped
#      network_mode: service:tdarr
#      environment:
#        - TZ=Europe/London
#        - PUID=1000
#        - PGID=1000
#        - UMASK_SET=002
#        - nodeID=MainNode
#        - serverIP=0.0.0.0
#        - serverPort=8266
#      volumes:
#        - /media/faiyt/d/config/tdarr/configs:/app/configs
#        - /media/faiyt/d/config/tdarr/logs:/app/logs
#        - /transcode_cache:/temp
#        - /d:/d
#        - /e:/e
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=1000
    ports:
      - 13378:80
    volumes:
      - /media/faiyt/f/books/audiobooks/:/audiobooks
      - /media/faiyt/d/books/podcasts:/podcasts
      - /media/faiyt/d/books/written:/written
      - /media/faiyt/f/config/audiobookshelf/:/config
      - /media/faiyt/f/config/audiobookshelf/metadata>:/metadata
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    cpu_count: 4
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /media/faiyt/f/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /media/faiyt/f/config/nextcloud/:/config
      - /media/faiyt/f/config/nextcloud-data:/data
    ports:
      - 1443:443
    restart: unless-stopped
